### ISSUE TITLE
Basic commands

### ISSUE THREAD

**Issue by michaelreid** [edvorg/yet-another-craft#1]
Hello

What are the basic commands for playing this game? I'd like to play it with my son and also learn to code at the same time. 

Thanks!
Michael

**Comment by edvorg** [comment]
Hi. It's very simplified version just for educational purposes. You may select units by clicking on it, you may select all units of one type by clicking on unit twice. You may send selected units to arrive at some point at map or attack other's units. If you select your command centre, you will see three command types: 1 repair command centre by spending your minerals 2 build more units for minerals 3 harvest more minerals. That's it and currently that's all. You are always welcome to help hacking on it and send any PRs :)
