### ISSUE TITLE
[Run instruction]

### ISSUE THREAD

**Issue by ThinhPTran** [edvorg/yet-another-craft#3]
Dear Edvorg, 

I tried to run lein figwheel and browse to 0.0.0.0:3449 and 0.0.0.0:3000 but I don't see anything. Would you please show me the way to run. 

Best regards, 
Thinh P. Tran

**Comment by edvorg** [comment]
Hi. You could just build it with `lein uberjar` and the run the jar in target directory by `java -jar yet-another-craft.jar`. Please respond me if it does solve your problem.

Edward.

**Comment by ThinhPTran** [comment]
Hallo edvorg. I did run lein uberjar and try to run java -jar yet-another-craft.jar. Then I browse to 0.0.0.0:3000/thinh. :-D . It runs. I try with lein figwheel but I don't see anything except fork me on github. :-D. Wish you a good day.

**Comment by edvorg** [comment]
Hi. We should investigate this. Last time I ran it in dev mode, it worked
well. I will check that when I get a chance.
